"""Interactive setup for the Python edition.

The Apps Script edition exists for people who should never see a terminal.
This is for the tier above that: someone comfortable running a command, who
should still not have to learn YAML, hunt for the app-password page, or
discover a bad API key an hour later via a failed cron run.

So every credential is verified at the moment it is entered, and the schema is
built by asking what each field means in plain English — the same idea as the
Apps Script Fields tab.

The pure functions here (env merging, YAML generation, credential checks) are
kept free of prompting so they can be tested without a TTY.
"""

from __future__ import annotations

import json
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from pathlib import Path

GEMINI_MODELS_URL = "https://generativelanguage.googleapis.com/v1beta/models"
APP_PASSWORD_URL = "https://myaccount.google.com/apppasswords"
GEMINI_KEY_URL = "https://aistudio.google.com/apikey"

# Plain-English type -> the schema shorthand the llm extractor understands.
TYPE_CHOICES: dict[str, str] = {
    "text": "string",
    "number": "number",
    "whole number": "integer",
    "date": "date",
    "yes/no": "boolean",
    "currency code": "currency",
}


@dataclass
class Field:
    name: str
    type: str  # a TYPE_CHOICES value, e.g. "string"
    description: str


# -- credential checks ------------------------------------------------------


def verify_gemini_key(key: str, timeout: float = 10.0) -> tuple[bool, str]:
    """Check a Gemini key against models.list, which costs no quota.

    Uses urllib rather than google-genai so the check works before the `llm`
    extra is installed.
    """
    url = f"{GEMINI_MODELS_URL}?key={urllib.parse.quote(key)}"
    try:
        with urllib.request.urlopen(url, timeout=timeout) as resp:
            return resp.status == 200, "ok"
    except urllib.error.HTTPError as exc:
        if exc.code in (400, 401, 403):
            return False, "Google rejected that key. Check for a stray space."
        return False, f"Google returned {exc.code}."
    except (urllib.error.URLError, TimeoutError) as exc:
        return False, f"Could not reach Google ({exc}). Check your connection."


def verify_imap(host: str, user: str, password: str, port: int = 993) -> tuple[bool, str]:
    """Check IMAP credentials by logging in and out again."""
    import imaplib

    try:
        conn = imaplib.IMAP4_SSL(host, port)
    except OSError as exc:
        return False, f"Could not reach {host}:{port} ({exc})."
    try:
        conn.login(user, password)
        conn.logout()
        return True, "ok"
    except imaplib.IMAP4.error as exc:
        detail = str(exc)
        if "credentials" in detail.lower() or "auth" in detail.lower():
            return False, (
                "Login refused. On Gmail an account password will not work — "
                f"you need an app password from {APP_PASSWORD_URL} "
                "(requires 2-Step Verification)."
            )
        return False, detail


# -- file generation --------------------------------------------------------


def merge_env(existing: str, updates: dict[str, str]) -> str:
    """Set keys in a .env, replacing any existing assignment in place.

    Order and comments are preserved so a hand-edited file survives a re-run
    of the wizard.
    """
    lines = existing.splitlines()
    remaining = dict(updates)

    for i, line in enumerate(lines):
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key = stripped.split("=", 1)[0].strip()
        if key in remaining:
            lines[i] = f"{key}={remaining.pop(key)}"

    if remaining:
        if lines and lines[-1].strip():
            lines.append("")
        for key, value in remaining.items():
            lines.append(f"{key}={value}")

    return "\n".join(lines).rstrip("\n") + "\n"


def build_pipeline_yaml(
    *,
    name: str,
    source: str,
    fields: list[Field],
    sink: str,
    gmail_search: str = "has:attachment filename:pdf",
    local_path: str = "./samples",
    csv_path: str = "out/records.csv",
    dedupe_key: str = "_uid",
    limit: int = 20,
    schema_ref: str = "./.docufunnel-schema.json",
) -> str:
    """Emit a pipeline config. Written by hand rather than dumped by PyYAML so
    the comments that explain each choice survive into the file the user then
    edits.
    """
    out: list[str] = [
        f"# yaml-language-server: $schema={schema_ref}",
        "# Generated by `docufunnel setup`. Safe to edit.",
        f"name: {name}",
        "",
        f"limit: {limit}",
        "on_error: skip",
        "",
    ]

    if source == "imap":
        out += [
            "source:",
            "  type: imap",
            "  host: imap.gmail.com",
            "  user: ${IMAP_USER}",
            "  password: ${IMAP_PASSWORD}",
            f'  gmail_search: "{gmail_search}"',
            '  filename_glob: "*.pdf"',
            "  # Marks mail done with a Gmail label, and excludes it from the",
            "  # next search server-side.",
            "  processed: keyword",
            "",
        ]
    else:
        out += [
            "source:",
            "  type: local",
            f"  path: {local_path}",
            '  glob: "**/*.pdf"',
            "  state_file: .state/seen.json",
            "",
        ]

    out += [
        "normalize:",
        "  # Raw file straight to the model: layout survives and scanned pages",
        "  # work without OCR, at roughly 258 tokens per page. Switch to",
        "  # `markitdown` for cheaper text-only extraction at volume.",
        "  type: passthrough",
        "",
        "extract:",
        "  type: llm",
        "  model: gemini-2.5-flash",
        "  schema:",
    ]
    for field in fields:
        if field.description:
            out.append(f"    {field.name}:")
            out.append(f"      type: {field.type}")
            out.append(f"      description: {json.dumps(field.description)}")
        else:
            out.append(f"    {field.name}: {field.type}")
    out.append("")

    if sink == "gsheet":
        out += [
            "sink:",
            "  type: gsheet",
            "  spreadsheet_id: ${SHEET_ID}",
            '  tab: "{{year}}"',
            f"  dedupe_key: {dedupe_key}",
            "",
        ]
    else:
        out += [
            "sink:",
            f"  type: {sink}",
            f"  path: {csv_path}",
            f"  dedupe_key: {dedupe_key}",
            "",
        ]

    return "\n".join(out)


def suggest_dedupe_key(fields: list[Field]) -> str:
    """Prefer a business identifier over the content hash when one is present:
    the same invoice re-sent as a differently-named file should still count as
    a duplicate, which a hash cannot see.
    """
    for field in fields:
        lowered = field.name.lower()
        if any(token in lowered for token in ("invoice_no", "invoice_number", "number", "id", "ref")):
            return field.name
    return "_uid"


def write_files(
    target: Path,
    yaml_text: str,
    env_updates: dict[str, str],
    schema: dict,
) -> list[Path]:
    """Write the pipeline, the .env and the editor schema.

    Every returned path is resolved, so a caller printing them does not get a
    mix of absolute and cwd-relative entries.
    """
    written: list[Path] = []

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(yaml_text)
    written.append(target.resolve())

    if env_updates:
        env_path = Path(".env")
        existing = env_path.read_text() if env_path.exists() else ""
        env_path.write_text(merge_env(existing, env_updates))
        written.append(env_path.resolve())

    schema_path = target.parent / ".docufunnel-schema.json"
    schema_path.write_text(json.dumps(schema, indent=2) + "\n")
    written.append(schema_path.resolve())

    return written


# -- interactive driver -----------------------------------------------------


def _ask(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    answer = input(f"{prompt}{suffix}: ").strip()
    return answer or default


def _ask_secret(prompt: str) -> str:
    from getpass import getpass

    # getpass so a shoulder-surfer and the shell history both miss it.
    return getpass(f"{prompt}: ").strip()


def _ask_choice(prompt: str, options: list[tuple[str, str]], default: int = 1) -> str:
    print(f"\n{prompt}")
    for i, (_, label) in enumerate(options, 1):
        mark = " (recommended)" if i == default else ""
        print(f"  {i}. {label}{mark}")
    while True:
        raw = input(f"choice [{default}]: ").strip()
        if not raw:
            return options[default - 1][0]
        if raw.isdigit() and 1 <= int(raw) <= len(options):
            return options[int(raw) - 1][0]
        print(f"Enter 1-{len(options)}.")


def _ask_verified(label: str, check, attempts: int = 3) -> str | None:
    """Prompt for a secret and verify it before accepting.

    Verifying here rather than at first run is the point of the wizard: a
    typo'd key otherwise surfaces as a failed scheduled run hours later.
    """
    for remaining in range(attempts, 0, -1):
        value = _ask_secret(label)
        if not value:
            return None
        ok, message = check(value)
        if ok:
            print("  verified.")
            return value
        print(f"  {message}")
        if remaining > 1:
            print(f"  {remaining - 1} attempt(s) left, or press Enter to skip.")
    return None


def _ask_fields() -> list[Field]:
    """Collect what to extract, described in plain English.

    The description is what the model actually keys off, so it matters more
    than the field name; the prompt says so.
    """
    print("\nWhat should be pulled out of each document?")
    print("Give each thing a short name, a type, and a plain-English note")
    print("saying what it is — the note is what the AI reads.\n")
    print("Press Enter on an empty name when you are done.")

    type_names = list(TYPE_CHOICES)
    fields: list[Field] = []
    suggestions = [
        ("invoice_no", "text", "The invoice or receipt number"),
        ("invoice_date", "date", "The date printed on the document"),
        ("vendor_name", "text", "The company that issued the document"),
        ("total", "number", "The grand total including tax"),
    ]

    if _ask("\nStart from the usual invoice fields? (y/n)", "y").lower().startswith("y"):
        for name, type_label, description in suggestions:
            fields.append(Field(name, TYPE_CHOICES[type_label], description))
            print(f"  added {name} ({type_label})")

    while True:
        name = _ask("\nField name (Enter to finish)")
        if not name:
            break
        name = name.replace(" ", "_").lower()
        print(f"  types: {', '.join(type_names)}")
        type_label = _ask("  type", "text").lower()
        if type_label not in TYPE_CHOICES:
            print(f"  '{type_label}' is not a type; using text.")
            type_label = "text"
        description = _ask("  what is it, in plain English")
        fields.append(Field(name, TYPE_CHOICES[type_label], description))

    return fields


def run_wizard(output: str | None = None) -> int:
    print("docufunnel setup\n" + "=" * 60)
    print("This asks a handful of questions, checks every credential as you")
    print("enter it, and writes a pipeline you can run straight away.\n")

    env: dict[str, str] = {}

    source = _ask_choice(
        "Where do the documents come from?",
        [
            ("imap", "Gmail — needs an app password, no Google Cloud project"),
            ("local", "A folder on this machine"),
        ],
    )

    gmail_search = "has:attachment filename:pdf"
    local_path = "./samples"

    if source == "imap":
        user = _ask("\nGmail address")
        print(f"\nAn app password, not your account password. Create one at:\n  {APP_PASSWORD_URL}")
        print("(2-Step Verification must be on for that page to appear.)")
        password = _ask_verified(
            "App password",
            lambda pw: verify_imap("imap.gmail.com", user, pw),
        )
        if not password:
            print("\nNo working app password, so stopping here — the pipeline would")
            print("not be able to read any mail. Re-run when you have one.")
            return 2
        env["IMAP_USER"] = user
        env["IMAP_PASSWORD"] = password
        print("\nWhich emails? This is a normal Gmail search.")
        gmail_search = _ask("Gmail search", gmail_search)
    else:
        local_path = _ask("\nFolder holding the documents", local_path)

    print(f"\nA Gemini API key does the extraction. Free, about 30 seconds:\n  {GEMINI_KEY_URL}")
    api_key = _ask_verified("Gemini API key", verify_gemini_key)
    if not api_key:
        print("\nNo working key, so stopping here — extraction needs one.")
        return 2
    env["GEMINI_API_KEY"] = api_key

    fields = _ask_fields()
    if not fields:
        print("\nNothing to extract, so stopping. Re-run and add at least one field.")
        return 2

    sink = _ask_choice(
        "Where should the extracted rows go?",
        [
            ("csv", "A CSV file — nothing else to set up"),
            ("gsheet", "A Google Sheet — needs a service account"),
        ],
    )
    csv_path = "out/records.csv"
    if sink == "gsheet":
        sheet_id = _ask("\nSpreadsheet ID (the part of the URL after /d/)")
        env["SHEET_ID"] = sheet_id
        print("\nOne more step for Sheets: create a service account in the Google")
        print("Cloud console, download its JSON key, and set")
        print("GOOGLE_SERVICE_ACCOUNT_JSON in .env to the file path. Then share")
        print("the sheet with that account's client_email as an Editor.")
        print("No OAuth consent screen is involved.")
    else:
        csv_path = _ask("\nCSV file to write", csv_path)

    dedupe = suggest_dedupe_key(fields)
    name = _ask("\nName for this pipeline", "my-documents")
    target = Path(output or f"pipelines/{name}.yaml")

    if target.exists() and not _ask(f"\n{target} exists. Overwrite? (y/n)", "n").lower().startswith("y"):
        print("Left it alone.")
        return 1

    from .introspect import json_schema

    yaml_text = build_pipeline_yaml(
        name=name,
        source=source,
        fields=fields,
        sink=sink,
        gmail_search=gmail_search,
        local_path=local_path,
        csv_path=csv_path,
        dedupe_key=dedupe,
    )
    written = write_files(target, yaml_text, env, json_schema())

    print("\n" + "=" * 60)
    for path in written:
        # Shorter to read when the file is under the working directory.
        try:
            shown = path.relative_to(Path.cwd())
        except ValueError:
            shown = path
        print(f"  wrote {shown}")
    print(f"\nDuplicate rows will be skipped by '{dedupe}'.")
    if env:
        print(".env holds your credentials and is gitignored — never commit it.")

    print("\nTry it, reading real mail but writing nothing:")
    print(f"  docufunnel run {target} --limit 3 --dry-run")
    print("\nThen for real:")
    print(f"  docufunnel run {target}")
    return 0
